### ISSUE TITLE
fontawesome-pro Module not found

### ISSUE THREAD

**Issue by osyanin** [GetScatter/ScatterEmbed#40]
Subj.

**Comment by Soleone** [comment]
I received the same error and just replaced it with `fontawesome-free` in two places:

1. In the [package.json](https://github.com/GetScatter/ScatterEmbed/blob/8ad79034ba66a3ff55e4fc98baccc38fb71c2068/package.json#L47)
2. In [main.js](https://github.com/GetScatter/ScatterEmbed/blob/8ad79034ba66a3ff55e4fc98baccc38fb71c2068/src/main.js#L33)

After that it seemed to work fine.

**Comment by ramijames** [comment]
This is because we are using the PRO set and you guys do not have access to the token which allows this to be built.
